---
title: "Parallel Playground"
author: "Elke Windschitl"
date: "2023-02-06"
output: html_document
---

```{r setup, echo = TRUE, message = FALSE, warning = TRUE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(parallel)
library(furrr)
library(raster)
library(tictoc)
```

## Do a slow thing

```{r}
# make a list of files
rast_fs <- list.files('data',full.names = TRUE)

# read in raster
r <- raster::raster(rast_fs[1])
plot(r)

df <- as.data.frame(r, xy = TRUE) %>% 
  setNames(c('x', 'y', 'z')) %>% 
  drop_na() %>% 
  mutate(type = case_when(z < .1 ~ 'low',
                          z < .25 ~ 'medium',
                          z < .5 ~ 'high',
                          TRUE ~ 'vhi')) # anything else is high

summary_df <- df %>% 
  group_by(type) %>% 
  summarize(n_cells = n())
```


### For Loop

```{r}
system.time({ # request time elapsed for the following

out_list_loop <- vector('list', length = length(rast_fs)) %>% 
  setNames(rast_fs)

for(f in rast_fs) {
  r <- raster::raster(f)

df <- as.data.frame(r, xy = TRUE) %>% 
  setNames(c('x', 'y', 'z')) %>% 
  drop_na() %>% 
  mutate(type = case_when(z < .1 ~ 'low',
                          z < .25 ~ 'medium',
                          z < .5 ~ 'high',
                          TRUE ~ 'vhi')) 
summary_df <- df %>% 
  group_by(type) %>% 
  summarize(n_cells = n(),
            f = basename(f))

out_list_loop[[f]] <- summary_df
}
})

out_df_loop <- bind_rows(out_list_loop)
```

## Create a function

```{r}
process_rast_file <- function(f) {
  r <- raster::raster(r)
  df <- as.data.frame(r, xy = TRUE) %>% 
    setNames(c('x', 'y', 'z')) %>% 
    drop_na() %>% 
    mutate(type = case_when(z < .1 ~ "low",
                            z < .25 ~ "medium",
                            z < .5 ~ "high",
                            TRUE ~ "vhi"))
  summary_df <- df %>% 
    group_by(type) %>% 
    summarize(n_cells = n(),
              f = basename(f))
  return(summary_df)
}
```

### lapply

```{r}
tic()
out_list_lapply <- lapply(X = rast_fs, FUN = process_rast_file)
toc()
```

### mclapply

```{r}
tic()
out_list_mcapply <- parallel::mclapply(X = rast_fs, FUN = process_rast_file, mc.cores = 4)
toc()
```

### purrr

```{r}
tic()
out_list_purrr <- purrr::map(.x = rast_fs, .f = process_rast_file)
toc()
```

### furrr

```{r}
plan(multisession, workers = 4)
tic()
out_list_purrr <- furrr::future_map(.x = rast_fs, .f = process_rast_file)
toc()
```

